#!/usr/bin/env bash
# Is the host on the network

# Check if an IP address is provided as an argument
if [ $# -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# IP address passed as argument
ip_address=$1

# Ping the IP address 5 times
ping -c 5 "$ip_address"

