#!/usr/bin/env bash
#A Bash script that displays all active IPv4 IPs on the machine it’s executed on.

# Get IPv4 addresses from 'ip' command output, filter out loopback and inactive addresses, and display
ip -o addr show | awk '$3 == "inet" && $2 !~ /^lo/ {print $4}' | cut -d'/' -f1

