#!/usr/bin/env bash
#A Bash script that listens on port 98 on localhost


# Check if script is run as root
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root" 
    exit 1
fi

# Listen on port 98 on localhost
nc -l -p 98 -k

